### ISSUE TITLE
APE hangs on RMUinit

### ISSUE THREAD

**Issue by enginsheer** [meklort/bcm5719-fw#96]
Hello,
First of all thank you for all your hard work, this codebase is a gem. 
I have been trying to play around with the APE functionality and I notice that even though i follow all instructions on how 
to unload the driver etc the APE fails to load properly. 
With some debugging i located  that the APE seems to stop in rmu.c, initRMU function, apparently waiting for 

APE_PERI.BmcToNcRxControl.bits.ResetBad to turn 0 from 1 in an endless loop.

Would you happen to have any insight for why this could happen?

Thanks!

**Comment by meklort** [comment]
I've seen a couple of cases where a reset will fail in some cases, and wouldn't surprised if that's one of them. Most of the while loops blocking on hardware need to be changed to have a timeout similar to ae0d138e0af73f197e8e5c76bf378ce18a0394a6.

In the case of initRMU, setting ResetBad should probably only needs to happen when APE_PERI.BmcToNcRxStatus.bits.Bad is set. That said, it should be ok to still set ResetBad. In your case, it sounds like the hardware might not be enabled or clocked for some reason, and so the register doesn't self-clear.

Do note that It's been a while since I've used the instructions in the readme - you may need to power cycle the BCM5719 after writing stage1 before everything works as expected.

**Comment by meklort** [comment]
I've run into a similar issue when resetting while powering down the host. I'm not exactly sure the cause or the best way to handle it, but I've updated the code to break out of the infinite loop you mentioned (and another).

I'll continue testing and see if this is sufficient to make things work, however I expect the next time it happens I may need to do a more forceful reset in the timeout case.

**Comment by enginsheer** [comment]
Hi Evan,

I will check out the new revision and see if it solves the issue for me as
well.
Again thanks a lot for letting me know and all your hard work in this repo,
it's amazing how little documentation exists to use the ape functionality
officially, it's almost like they created hardware never to be used.

Στις Τρί, 27 Οκτ 2020, 10:53 μ.μ. ο χρήστης Evan Lojewski <
notifications@github.com> έγραψε:
